name: Upload files to an archive.org item - fork
author: qoijj
description: Automatically save files with the Internet Archive

branding:
  icon: upload-cloud
  color: white

inputs:
  access-key:
    description: Your archive.org access key.
    required: true
  secret-key:
    description: Your archive.org secret key
    required: true
  identifier:
    description: The unique identifier of the archive.org item where the file will be stored
    required: true
  files:
    description: The file or folder path inside the action's filesystem to upload
    required: true

runs:
  using: "composite"
  steps:
    - id: setup-python
      name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version:  3.9

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install internetarchive retry
      shell: bash

    - id: upload-files
      name: Upload files
      run: |
        import logging
        import os

        import internetarchive
        from retry import retry

        access_key = os.getenv("access-key")
        secret_key = os.getenv("secret-key")
        identifier = os.getenv("identifier")
        files = os.getenv("files")

        logging.basicConfig(level="DEBUG", format="%(asctime)s - %(name)s - %(message)s")
        logger = logging.getLogger(__name__)

        logger.debug(f"Uploading {files}")
        kwargs = dict(
            access_key=access_key,
            secret_key=secret_key,
            verbose=True,
            files=files,
        )
        internetarchive.upload(identifier, **kwargs)
      shell: python
      env:
          access-key: ${{ inputs.access-key }}
          secret-key: ${{ inputs.secret-key }}
          identifier: ${{ inputs.identifier }}
          files: ${{ inputs.files }}
